var keywordData = [
  {
    "순위": 1,
    "제목": "[단독] 빗썸 ‘62조원 비트코인 오지급 사고’ 막을 수 있었다",
    "추천점수": 23.0,
    "키워드": "단독, 지급, 사고",
    "카테고리": "경제",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/005/0001830958?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 2,
    "제목": "[단독] 국세청, 이민자 수천명 개인자산내역 열람 논란",
    "추천점수": 20.0,
    "키워드": "단독, 논란, 논란",
    "카테고리": "경제",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/005/0001830959?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 3,
    "제목": "아르헨 정부, 새 물가지수 도입 중단에 '통계 신뢰' 논란 - fnnews.com",
    "추천점수": 10.0,
    "키워드": "논란, 논란",
    "카테고리": "경제",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE1zTWYyQnRHbjN6UG40X3VYMG1FSW9idWhxN3E1WUFhRnNReFNVRmRvSlpWRk5WV0syaFJzcC1pUUVLZnNwVFRtUjJtS0l6My1RaU5KZW9SMnI0UdIBXkFVX3lxTFBSWngzOUF3SmxFZVpfc2xzdGFHRXhoSVNvbmZqM1hQVzZGLWo4a1RIRjdvSDg2dnNLZXdwVXV3VUQyeEFmNFlGUFlyMzJnVU8wS09LRkk2N0MtQ0Fob0E?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 4,
    "제목": "빗썸 \"비트코인 오지급 보상 시작‥회수 못 한 비트코인 125개\" - MBC 뉴스",
    "추천점수": 10.0,
    "키워드": "지급",
    "카테고리": "경제",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMidEFVX3lxTE5qRkszOVBQbjZxTFZENm5NRlhDV1RFWEdaV1NpejMzMjYyQUR3d0NuT1N6VW1ncGVDQ2xQaTdQaHk1NVA2cl9OT3N3dXoxVXcxWHhlb19VTjZpNkdTeFBvVzF2bnZKMzl2bmNVcU83VUdUY1Jf0gF0QVVfeXFMTUV6Nlc1SVp5dkd3aWFmMklUMkVPb0FVS3B5UUVhNTlUTkhmMnhVa1BxTjFNbDFlVlh4bW0zTlJUZ0FiRlpPcjhVdnVJTkFKa1NtanJDYzhNbzNUZ3hnM3p6Z0FUZGRXQWE1OTRaOEZFM1Vwel8?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 5,
    "제목": "[단독] ‘윤핵관’에 장검 건네려 한 근우회장… 신천지 대선 전 尹 접촉 시도 정황",
    "추천점수": 10.0,
    "키워드": "단독",
    "카테고리": "경제",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/005/0001830972?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 6,
    "제목": "[단독]신천지 '정교유착 연결고리' 이희자, 박성중에 장검 전달",
    "추천점수": 10.0,
    "키워드": "단독",
    "카테고리": "경제",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/079/0004113656?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 7,
    "제목": "[단독] 소방관으로 돌아간 전직 의원의 호소 \"이태원 참사 재수사, 너무도 잔인\"",
    "추천점수": 10.0,
    "키워드": "단독",
    "카테고리": "장년",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/469/0000913439?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 8,
    "제목": "`누구를 위한 복지인가`, 중산층도 받는 기초연금…실업급여는 적자 논란 - 매일신문",
    "추천점수": 10.0,
    "키워드": "논란, 논란",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiYkFVX3lxTE9qQnFSR1kzYjFBay11a3lqUUNMMFh6U1Jja1RKN2x0czBXMjdTd0lHeUduc1YzUE85WEticFg5QlV1OVMyeGl5WDA5bkVwZ3NHQUwyTVNDVUFIOHZob0l5SENB?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 9,
    "제목": "이준석-전한길, ‘부정선거’ 공개토론회 25일 개최 추진",
    "추천점수": 7.0,
    "키워드": "공개",
    "카테고리": "장년",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/056/0012121140?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 10,
    "제목": "[칼럼]대한상의 보도자료 '참사', 고의성이 의심되는 이유",
    "추천점수": 3.0,
    "키워드": "이유",
    "카테고리": "경제",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/079/0004113652?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 11,
    "제목": "케빈 워시는 친(親)비트코인 인사?…“가격 변동성 너무 커 활용도 떨어져” - 조선일보",
    "추천점수": 3.0,
    "키워드": "변동",
    "카테고리": "경제",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMijgFBVV95cUxPdGsyWDZvNmItOHVtT0g3QnRhUnZNQ2ZHUlFNYVFya2ZHYzdTdUs2ZXhHV0RUWU5nMmFnazNUdVB6T2Q2TW5ldXVvbEhGTlJZbjMxeFByZlZKZkFtMENWb3VpU1FQSFFoTEtlanpEdkFVRHpzbE1zVXZnb0xfSW9sME5nMkd5cHI5eXh5Wm5R0gGiAUFVX3lxTFBpVk9oVHVDa29xRjdOSVZ6MmNqZ3ZuVGE5T0tmVXA1elJ3RGo0QUkyc1RCV0NvZ1AzQ3I5MGZ5TzMtdXZLQlp4QXRJUDhMaXc5S3RVOFVuQmxIbGh3SmJaZzFoLWtKMkdWMEliaTI3cVJKM3BUd2I4dENrSWlTamYtS1N2Y3gxaExycEx4eGkwUms2UkxhRnpncnprWGUxT2JVQQ?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 12,
    "제목": "비트코인, 3년만에 '최악의 한주'…자유낙하 이유 두고 백가쟁명 - yna.co.kr",
    "추천점수": 3.0,
    "키워드": "이유",
    "카테고리": "경제",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiW0FVX3lxTE5VRjU2YTh2Y0ZLRlcyMUxZMV8wS1ZIRUl1RERVOWIyYlFhME9ZSFRQcnNWVlRabTVCQTFWSkhsOF9CSlVLUnhtcGJ2ZTIxSk5Ua2pGQ2hubWtTRUXSAWBBVV95cUxQeGdteGpzMFE5MTl6WXkzdEFDTHV5TjBtMnVZQU9TRDlRTHdZdXB0RlNtaTVkSTB0T0dWSXdrVU5vNnJ6MjlXTE9XOHpKQnIwTUhyUTdvdkNBYm9Nc19Sanc?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 13,
    "제목": "치매 예방 뇌 운동부터 자세 교정까지... 강서구, 이소연 교수와 한영훈 교정운동 코디네이터 진행 '운동 인문학' 운영 - 한국강사신문",
    "추천점수": 3.0,
    "키워드": "운동",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMicEFVX3lxTE83Uzdlc1hIRGtNdEpTUzQycGRXMXJiQ3BRVDB1aGEtSDVNbXozOFhubTJsbm1xQXZ1YTdvcENZdGtDOXRER2NNdS1OMGFfUlFUcU8xWnZKZzA1UDNlZTJ0TE9nclhnbTBQTDJmVEIzblg?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 14,
    "제목": "韓증시 시가총액, 독일 이어 대만도 추월 - mbnmoney.mbn.co.kr",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "경제",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiaEFVX3lxTE45QjNGZWp1MWNYM0ZmQW52UlZpcVhSLWlLTmVuTXByeUlvWEVnTmcyS0VHUmtjWFQ2UDNkWE1RcENlT1ZGb2x4ckVkWjVhN3NOcjA4VUZRX3I2M2ZpX2lzV2FrWU9zZXp5?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 15,
    "제목": "두쫀쿠 먹을 돈으로 주식 사라? 코스피 5000시대, 투자로 내몰린 청년들 - 경향신문",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "경제",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE5MeWgyUUw1TVEwbERqcURld3ZORURVWlNpMUNObTV6bEk5MC1BSjM2R2ppNHc0Z2QyQjdxal95OFl4eFA4QTFPV1pKYWVtRUZIaUctd2dtNTFVUdIBX0FVX3lxTFAyaHl3TzVqeklGR3pKdmNqQmtTSGZHZTVBSlFSelpZSnZqN1BESzRWQkxJdThUV2J0NEtVaVZmTDNySlpQcUNnQlpvb3JGcmZKNFl4WjJkcVNkN1NrV1Vj?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 16,
    "제목": "\"그렇게나 올랐어? 집 말고 주식 살걸\"…돈이 움직이기 시작했다 - 머니투데이",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "경제",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMia0FVX3lxTE9FTlhLNy1ldG5rZm9rSkFnMVI5enNXMzM3dWU0N2xqTDd4bDlMVUYyMzN4MXcyTE92ZUpLSHpieDhENzlQVUpUV1JuQVhQMmNzSkZzSllHcm02TUp0VDl2T1QtVVQ4MUd2eWJV?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 17,
    "제목": "숙소 못구해 차안서 가스 난로…덕유산 등산 온 父子 2명 사망",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "경제",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/005/0001830860?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 18,
    "제목": "주식으로 일확천금 노린다? 사실, 투자하는 MZ 큰 그림은... - v.daum.net",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "경제",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiT0FVX3lxTE5IQTE4LUtaVW1JVldENEJxZzhaVkp0OHB3enMzX3dkZjRJYVNNRkF6RlR0Um5qTWFYOXBPSFNfQjhpVVNyYUNWUmlhNWw3bkE?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 19,
    "제목": "먹거리 물가 상승 - 네이트",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "경제",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiU0FVX3lxTE92OEcwOE5qSzlVU0xzbTlaV2xocUdZaXNQalhIN201SXF6TURSM01nd243RmswYkFUSWFHN3k2MmhiNjlyek82dVdyWGpxWmJ3c0pR?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 20,
    "제목": "성장률 상승? 착각하지 마라…‘물가 상승빨’로 명목성장률↑ 실질은 정체 - 매일경제",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "경제",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiVEFVX3lxTE9DMlhuLWl4OEEydHd6MHVmTU1qVXJabjktWXljeWw0VUJVX3luV2c5RDNHdnRnZmhPcmFNVE1FR0IyT2JxdVRPcmJ3cU8xNlBQcnl4dg?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 21,
    "제목": "이준석-전한길 '부정선거' 주제 토론…변수는 경찰 수사[영상]",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "경제",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/079/0004113660?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 22,
    "제목": "'불륜 증거 찾겠다'…블랙박스 메모리 훔친 40대 선고유예",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "경제",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/079/0004113586?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 23,
    "제목": "'상속세 탓 2400명 탈한국'? 국세청장 \"팩트체크 한다, 연평균 139명 수준\"",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "경제",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/079/0004113646?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 24,
    "제목": "“李대통령 설 선물 50만원에 팔아요”…당근 되팔이",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "경제",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/005/0001830977?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 25,
    "제목": "드림타워 카지노, 노인 일자리 창출사업 성금 2천만원 기탁 - 뉴스N제주",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMia0FVX3lxTE9CUU5QbWlLY2hNc1pWUHI5TXh2Skh2b3pxLWwtWUQ4MjlocHgwY1p4MnJSTXdjMi1VeWdEeWxINUVITWh5TW5jNDJta19FVW54alctSlN4dFBVVkZwbVJ5TDVqVHVBUXZwUXMw?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 26,
    "제목": "올해 전남 어르신 기초연금·경로당 운영비 등 증액 - 드림투데이",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiakFVX3lxTE1TeFEwMWd3TXFXSERlb0pyYjBVdjREZmJ2RzBHUklFTVlsWlZnQ21KS3NLbHdrWE5fZExDN0hKTy1HcXZycmtEYWhkSjJ3QmVuR1BFR3BGellQdktRS3RMclFWU0Fob0p2WHc?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 27,
    "제목": "울진읍, 2026년 노인일자리 사업 발대식 및 안전교육 - 경북신문",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiWEFVX3lxTFBTajNXN2VoMkQ5TWZnQVNrOUFzZEU2SWE5M2Q3elpxdXdPM0c1TWhQZUlCZTRKM1dBalU3aVpWMTF4NGRSUGpPWjBkVUpEYThMZFh4TE9oRzE?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 28,
    "제목": "광주 공공노인일자리 신청자 늘었는데 선발은 감소…\"경쟁 치열\" - yna.co.kr",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiYEFVX3lxTFB2XzlhWjdSSUNSY2FOVTRFbmNla2tjOExjNUxXajd6S01Qbm5WcmVpVXRwa2VZQmx0SHVSRnpEYUZVbDNYTnNoeDhGcHNsdWI1ckFPa21Bdy1OYklDUGF2UtIBYEFVX3lxTFB2XzlhWjdSSUNSY2FOVTRFbmNla2tjOExjNUxXajd6S01Qbm5WcmVpVXRwa2VZQmx0SHVSRnpEYUZVbDNYTnNoeDhGcHNsdWI1ckFPa21Bdy1OYklDUGF2Ug?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 29,
    "제목": "전남도, 노인복지에 1조7천998억 편성…맞춤형 돌봄·일자리 확대 - 시민의소리",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMia0FVX3lxTE5ZQXIyV0JFYXcwT0hUaHExOUdhZVdJcTZHWVlPMF92MHgyaHpFWTMtYklrWTdtMl9ITmFIN2dmaC10a2JIdlNMU3N4Qk9jczNzeGdIWUpvZ2VCdjVNc0VRRUpkLUZPSTlsaW80?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 30,
    "제목": "충남도, 노인 일자리 연계 탄소중립 실천 - 금강일보",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiakFVX3lxTE02WHRoNGpvTW1USlVLbmZqaHlnb3hKaV9ZWmRlU21KUXA3c2xtVHhiRTZ3WHJ6azdfQ01MYzRHRDhLRGhXaEV2YlpJWmJPRnd1NmdsQUg5M1ZXMFVyRFh4Vlh5Y0loMGh5SlE?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 31,
    "제목": "학생검진, 생애 주기별 건강검진으로 일원화 - 치과신문",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiZkFVX3lxTFBMNWRBakJiVVMweUZqSmR6QXRxRXhocnZxZWg5WHYtZnAwZ3pCZGRLem8tTXFhTVI5ZHBJUUN5QXpBQkF3UV82N2VvVzV2aUtObVFKSVZpOWtDYzBrLUNNdnE1UXRfQQ?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 32,
    "제목": "상주시치매안심센터, 찾아가는 뇌건강 교실 운영으로 치매 예방 강화 - 경북신문",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "장년",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiWEFVX3lxTE03ZG9oMWxCWDFrTTI2RUlVeWd3N3dGQVU3eXVCRkx5djcwTWpxVEd1Z2FxLWZFbFE5TkNrUkk2Qlg4S3dvcGQ4YldqdXIxM0hkemVTc3RVbTg?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 33,
    "제목": "“한덕수 벌벌 기어” 재판장 나섰다…내란재판 2라운드 [피고인 윤석열]㊷",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "장년",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/056/0012121081?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 34,
    "제목": "“차비 2천 원이 죄인가요?”…지갑 찾아준 요양보호사 ‘벌금형’ [잇슈#태그]",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "장년",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/056/0012121131?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 35,
    "제목": "[크랩] 동남아 대표 여행지 태국은 왜 ‘가성비’ 타이틀을 버렸을까?",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "장년",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/056/0012121104?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 36,
    "제목": "경주 문무대왕면 산불 진화율 85%…국가소방동원령 발령",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "장년",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/056/0012121142?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 37,
    "제목": "300억대 재산 노렸나...대만 102세 노인과 몰래 결혼한 60대 간병인",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "장년",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/469/0000913416?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 38,
    "제목": "목줄이 조이는 고통 속에서도 엄마개가 지켜낸 강아지 6남매",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "장년",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/469/0000913433?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 39,
    "제목": "서울 청년 5명 중 4명은 '내 집' 없다… 2030 무주택 '역대 최대'",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "장년",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/469/0000913449?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 40,
    "제목": "\"날 무시해\" 아내 흉기로 80여 차례 찔러 살해한 70대 '징역 18년'",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "장년",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/469/0000913380?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  }
];
var scraperStatus = {
  "youtube": "OK",
  "google": "OK",
  "naver": "OK"
};
