const keywordData = [
  {
    "순위": 1,
    "제목": "“객실 성행위, 1만명이 지켜봤다”…중국 호텔 ‘몰카’ 실시간 중계·유통 ‘충격’",
    "추천점수": 20.0,
    "키워드": "실시간, 충격",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/029/0003009658?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 2,
    "제목": "[속보] “펑소리 후 송전탑에 불길”…경주 문무대왕면 산불, 송전탑 발화 의혹",
    "추천점수": 17.0,
    "키워드": "속보, 의혹",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/029/0003009702?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 3,
    "제목": "팔뚝만한 텀블러 왜 갖고다녀?…자본주의 끝판왕이 허락한 ‘공짜 물’의 정신 [홍키자의 美쿡]",
    "추천점수": 13.0,
    "키워드": "공짜, 주의",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/009/0005634098?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 4,
    "제목": "삼전·SK하닉 호실적·성과급 지급에…4년만에 ‘세수 펑크’ 끝날까",
    "추천점수": 10.0,
    "키워드": "지급",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/009/0005634036?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 5,
    "제목": "경찰, '대통령실 PC 초기화 지시' 의혹 정진석 대면 조사 - MBC 뉴스",
    "추천점수": 10.0,
    "키워드": "의혹, 조사",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMid0FVX3lxTFBIVnl3alpjbnNwOGMySVZHMUhieW40YUFYYkE4dDhGaWZVNkRmRDZnN05NSWY0QlJNS3R3aHprYzdZUzNVdjA0SDl3NFpjZmI5YWstSi1NM3o0X1ViX1VUZ2FGcklTalBMVFN2WDg2VnBFYURNaTM00gF3QVVfeXFMTk1uQ0Q3SzU3Tmg4WURELVV1Zi1zMFBMWmxibFRud0FUZzRFWnQ2ZnFQdWJYZXU1UmpZWEg3MlRXQmJmSU9vbC1hUWVtdUpVQ2d3N2FxU2hrTnhzWHV5alRyMS1ZeV9QS2NnTkhTU1plNVVIOUJZTTg?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "https://news.google.com/rss/articles/CBMiW0FVX3lxTE4zaVdZRTJvTlhWR1IwM0lZU19NbW82QnlSdnJuZHByS2pEcXdoODlEMGhoOTY1MWJhMTNWeDZqbDVZdUh0eHFnTk5jSENUU2Q0b1RmWlR0T3pzcDA?oc=5",
    "뉴스기사2_날짜": "2026-02-08",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 6,
    "제목": "[속보] 경찰, ‘尹대통령실 PC 초기화’ 정진석 전 비서실장 피의자 소환 - v.daum.net",
    "추천점수": 10.0,
    "키워드": "속보",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiT0FVX3lxTFBub1ZSX0JWUWk5eDA5djZ4aGdxc0Vhc0dUUDhmU21JQWJtenRsNE13YmExWDhkVlR1VzZ6OVBONHQwTnFqMzRtZWhDeWo1anc?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "https://news.google.com/rss/articles/CBMiVkFVX3lxTE5MbWRNTnNWTFl5YTF6OXdoV3VYaWRSZThhLUs0ZWV4dUpKVG9Zc2tTSWhhcVNDSkJTNFRMM3NJSDFFNFc2MlFrVnZZM0xtNzNfUGVHSGJn?oc=5",
    "뉴스기사2_날짜": "2026-02-08",
    "뉴스기사3_URL": "https://news.google.com/rss/articles/CBMiW0FVX3lxTE4zaVdZRTJvTlhWR1IwM0lZU19NbW82QnlSdnJuZHByS2pEcXdoODlEMGhoOTY1MWJhMTNWeDZqbDVZdUh0eHFnTk5jSENUU2Q0b1RmWlR0T3pzcDA?oc=5",
    "뉴스기사3_날짜": "2026-02-08",
    "조회수": ""
  },
  {
    "순위": 7,
    "제목": "[속보] '尹대통령실 PC 초기화' 정진석, 경찰 피의자 출석 - 중앙일보",
    "추천점수": 10.0,
    "키워드": "속보",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiVkFVX3lxTE5MbWRNTnNWTFl5YTF6OXdoV3VYaWRSZThhLUs0ZWV4dUpKVG9Zc2tTSWhhcVNDSkJTNFRMM3NJSDFFNFc2MlFrVnZZM0xtNzNfUGVHSGJn?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "https://news.google.com/rss/articles/CBMiT0FVX3lxTFBub1ZSX0JWUWk5eDA5djZ4aGdxc0Vhc0dUUDhmU21JQWJtenRsNE13YmExWDhkVlR1VzZ6OVBONHQwTnFqMzRtZWhDeWo1anc?oc=5",
    "뉴스기사2_날짜": "2026-02-08",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 8,
    "제목": "[속보] 정원오 서울시장 출마선언 “멋지고 행복하고 편안한 서울 만들겠다”",
    "추천점수": 10.0,
    "키워드": "속보",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/029/0003009692?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 9,
    "제목": "경찰, ‘尹대통령실 PC 초기화 의혹’ 정진석 전 실장 소환 - KBS 뉴스",
    "추천점수": 7.0,
    "키워드": "의혹",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiW0FVX3lxTE4zaVdZRTJvTlhWR1IwM0lZU19NbW82QnlSdnJuZHByS2pEcXdoODlEMGhoOTY1MWJhMTNWeDZqbDVZdUh0eHFnTk5jSENUU2Q0b1RmWlR0T3pzcDA?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "https://news.google.com/rss/articles/CBMid0FVX3lxTFBIVnl3alpjbnNwOGMySVZHMUhieW40YUFYYkE4dDhGaWZVNkRmRDZnN05NSWY0QlJNS3R3aHprYzdZUzNVdjA0SDl3NFpjZmI5YWstSi1NM3o0X1ViX1VUZ2FGcklTalBMVFN2WDg2VnBFYURNaTM00gF3QVVfeXFMTk1uQ0Q3SzU3Tmg4WURELVV1Zi1zMFBMWmxibFRud0FUZzRFWnQ2ZnFQdWJYZXU1UmpZWEg3MlRXQmJmSU9vbC1hUWVtdUpVQ2d3N2FxU2hrTnhzWHV5alRyMS1ZeV9QS2NnTkhTU1plNVVIOUJZTTg?oc=5",
    "뉴스기사2_날짜": "2026-02-08",
    "뉴스기사3_URL": "https://news.google.com/rss/articles/CBMiT0FVX3lxTFBub1ZSX0JWUWk5eDA5djZ4aGdxc0Vhc0dUUDhmU21JQWJtenRsNE13YmExWDhkVlR1VzZ6OVBONHQwTnFqMzRtZWhDeWo1anc?oc=5",
    "뉴스기사3_날짜": "2026-02-08",
    "조회수": ""
  },
  {
    "순위": 10,
    "제목": "“용광로에 폐기” 지시 밝혀질까···‘대통령실 PC초기화 의혹’ 정진석 피의자 소환 - 경향신문",
    "추천점수": 7.0,
    "키워드": "의혹",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE94Rnd6Z2wwTzIzWV9QaDRZVkVpQ21td1JvVUFLajhuTmFWSzBzNzJkcllFVkxtWFRCNGZKWWlMSXFjZDlRREFHdmNkNEJHaVZaU09CLXU4Y0ZzQdIBX0FVX3lxTE5KdlpIc3VLT2s2Sk1JM2NPdm80MzM0ekhQQ3RvSkZxbWFZT2ppRFM1bW5FaGlObjNUV0U3WFVrLVlvNXdMbDAyVEg4RWszb25WR3JfM0N4QWwtZjRQVDNF?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "https://news.google.com/rss/articles/CBMiW0FVX3lxTE4zaVdZRTJvTlhWR1IwM0lZU19NbW82QnlSdnJuZHByS2pEcXdoODlEMGhoOTY1MWJhMTNWeDZqbDVZdUh0eHFnTk5jSENUU2Q0b1RmWlR0T3pzcDA?oc=5",
    "뉴스기사2_날짜": "2026-02-08",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 11,
    "제목": "'대통령실 PC 초기화 의혹' 정진석 경찰 소환...혐의 입증 주목",
    "추천점수": 7.0,
    "키워드": "의혹",
    "카테고리": "사회",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/052/0002312028?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 12,
    "제목": "사건사고/ 포항 호미곶 앞바다서 낚시객 익수…해경 구조에도 숨져 - 해사신문",
    "추천점수": 6.0,
    "키워드": "사고, 사건",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMia0FVX3lxTFB3T3ZIT05EbmkxclhRRmZFUGNOQlNiZnEzTzhfQ3NiRFhtcHN4TDNUQTduWTZfSzZEU3E3VEgxWWlhNzRwOW94eEd2ZS1FM0JzaVlxUTUydzI1UVhkMFAwODNvSmQwR2RKQ3o0?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 13,
    "제목": "어린이보호구역 전치 10주 교통사고 낸 운전자 처벌은? - 국제신문",
    "추천점수": 3.0,
    "키워드": "사고",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiiwFBVV95cUxOam0teW05MG1nd2pBMVAwcG52YjFFWjhEMUtTeFk5LWV6M1ZUbVNJbVVpMzk4dks5eVRvWndtdVUxMFptRkJlS3Vpd2YwUE1vbnhHaG9kSVplbEt2TUVhUWh4OGVtb00zZ2llbVlNSEw5RjlNM0NMcFFaSnhJTnY4aG80bGxpMWdYTUdF?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 14,
    "제목": "[인터뷰] “HVAC, 삼성의 차세대 핵심 성장 동력”…삼성전자, AI·초연결로 시장 주도권 잡는다",
    "추천점수": 3.0,
    "키워드": "주도권",
    "카테고리": NaN,
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.samsung.com/kr/%ec%9d%b8%ed%84%b0%eb%b7%b0-hvac-%ec%82%bc%ec%84%b1%ec%9d%98-%ec%b0%a8%ec%84%b8%eb%8c%80-%ed%95%b5%ec%8b%ac-%ec%84%b1%ec%9e%a5-%eb%8f%99%eb%a0%a5%ec%82%bc%ec%84%b1",
    "업로드일": "2026-02-06",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 15,
    "제목": "김경 ‘CES 출입증 사적유용’ 수사…9일 고발인 조사 - 동방일보",
    "추천점수": 3.0,
    "키워드": "조사",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMickFVX3lxTE00LUFQYW5reHV4WkwtUHA5alQ2andYY2Zpak13b0VPejlkdGxtbkNXOEdNR1RqUlpVcmpnN1dtWTVNaElSV29iYmZ1QlBYaWgwSGVDUmZBMThlYm5tTkxJYVZJWnN4dkZpQ0UwVlo4SWVnZw?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 16,
    "제목": "양주시 호명산에 산불 발생⋯헬기 투입 - 인천일보",
    "추천점수": 3.0,
    "키워드": "발생",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMicEFVX3lxTE5KdXVNTW9IXy1mMFlEZE1IRTFPWHJxUV9fRzAwY09ucmpKOS1RbXFJeUo3VGhXTTBxYzRaZTJaQ0Z2c0ZJNEJ4VmdvQ0ttaUZhS3I3SjNRaWhfTDRFU3ZXNXhWbUE0bVJyNnpNNUgyN2s?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 17,
    "제목": "경남 찾은 이 대통령 \"심장에만 피·영양 몰리면 살겠나\"",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": NaN,
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://www.ohmynews.com/NWS_Web/View/at_pg.aspx?CNTN_CD=A0003205197",
    "업로드일": "2026-02-06",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 18,
    "제목": "‘지역 주민 반발에…’ 부산시, 이슬람풍 정원 새 후보지 찾는다",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": NaN,
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/082/0001366123?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 19,
    "제목": "[내일날씨] 대체로 맑고 강추위…아침 최저 -15∼-4도 - yna.co.kr",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiW0FVX3lxTFBvSG1yUFhWYmI2YTEyMzVqeFR4Q2taUlJFcXhybkVldWtoV2FUVVlnTEZKV185NXFsNVZ4bVRTaDlRM0ZNMkZlSkwybzAxVjZ0ekNHLUZfUHB2UmPSAWBBVV95cUxQTU1DQVlJQ2taQjBNd0U5N1o4QVA5enA3MERPNWpNMFYxcXpfcHo4OVZ3WEpkMWRLS0JNTmE2dVdFeGVjZWZ6RFBYcGxaZDVjUHo1VldlWmg2SGhPdnpMUlU?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 20,
    "제목": "내일 아침까지 강추위...제주 산지 5~15cm 눈 [날씨] - v.daum.net",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiT0FVX3lxTE96RDZCeGtoalQwZ1NnMTAxTmtxVkJlNXJ3dXBaTXE3TWd1VjlRZ0xJOGNucEdscjFuVlRvbkVjV2d2UmE0ZFhKWGMtenhaV2c?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 21,
    "제목": "'똘똘한 한 채' 막을 확실한 방법...이 대통령을 응원합니다",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": NaN,
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://www.ohmynews.com/NWS_Web/View/at_pg.aspx?CNTN_CD=A0003204709",
    "업로드일": "2026-02-06",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 22,
    "제목": "조국 “민주당 13일까지 입장 없으면 합당 안 할 것”…민주 “10일 의총 후 입장 발표”",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": NaN,
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/449/0000334708?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 23,
    "제목": "버려진 400평 부동산, 그대로 방치했더니 생명이 자라났다",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": NaN,
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://www.khan.co.kr/article/202602061552001",
    "업로드일": "2026-02-06",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 24,
    "제목": "2030 청년들이 본 이 대통령·언론 '부동산 설전'...\"5월 9일 이후가 더 중요\"",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": NaN,
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://www.ohmynews.com/NWS_Web/View/at_pg.aspx?CNTN_CD=A0003205166",
    "업로드일": "2026-02-06",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 25,
    "제목": "내일 아침까지 냉동고 한파…낮부터 추위 풀려 - 네이트",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiXkFVX3lxTFBGTEtES0p6U0ROSFRPT1VVNU1oQ29HQjNSVjd6QVFBYU8yLURIb2s3cmVBNW9ZUTZ6cmxBUTJGU0J3d2l3NGhaSzlERWQzVmpwQ0xhMjRDdHF0RG1OTVE?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 26,
    "제목": "[날씨] 오늘도 매서운 추위…전국 영하권, 곳곳 눈 예보 - 서울와이어",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMibEFVX3lxTFBPU2xFaklhdFVIM2pDelZIbXBRT3duN1FEYWdPV0Rra3BIQ0QwQUItdW0yZ3U2bFZEYjJXcnRfWGVqb0NuMTVWenNBOWpoVEQ5MmZiSXFtcFZCeFhFSHNEYVd3T3BMWDlXemphTA?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 27,
    "제목": "2월 8일 일요일, 종로 1만 명 규모 집회 예정…교통 통제 예상 [교통] - econovill.com",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMibEFVX3lxTFA0WVFfY0NraHhCN2ZvX1JxSHIxWjJyaGQzVWRJSkVSNXVUMUR3elhmSHdvMTRpZXF4X2xBU1Y2RDNvWjFIWHZ6OUluclB4M1hKbUNiQXgycU01bUFTVmlfb0w3T21Dc3hjbFdOYw?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 28,
    "제목": "금고에 돈다발 우르르...도박사이트 운영 총책 송환",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "사회",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/052/0002311996?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 29,
    "제목": "[속보] 빗썸 \"비트코인 오지급 보상 시작…내일부터 수수료 면제\"",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": NaN,
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/082/0001366131?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 30,
    "제목": "새들의 무덤 전락한 ‘생태 도서관’ - 울산매일",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "사회",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiakFVX3lxTE1tbXZyZExBeVFLd29FZjBLZzV3UDNCWE51Y2xzNGNnWHI4U0laRVFrdUZxN3p3VXNzMFE3TkhjeEl1UmxneHdmbC1wNnlZdW9uN0dHNjJQbXZETkRyMDhKRF81eEZSbzJwUGfSAW5BVV95cUxQM05RWWRFYXgwTmZFX3JBOEExRVVnMXY4MTV1YjJIUXhvZ1FhRmVfY1dvODJaZ3V3ZnQ0dDBWWjZHSE9WT1RkZW1uMWhkVGtFWlROTEEtbWx4S2hCQ2JUMXhoVHZlZ2FCTk5wdkZhQQ?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  }
];
const scraperStatus = {
  "youtube": "OK",
  "google": "OK",
  "naver": "OK"
};
