var keywordData = [
  {
    "순위": 1,
    "제목": "경찰, '대통령실 PC 초기화 지시' 의혹 정진석 대면 조사 - MBC 뉴스",
    "추천점수": 10.0,
    "키워드": "의혹, 조사",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMid0FVX3lxTFBIVnl3alpjbnNwOGMySVZHMUhieW40YUFYYkE4dDhGaWZVNkRmRDZnN05NSWY0QlJNS3R3aHprYzdZUzNVdjA0SDl3NFpjZmI5YWstSi1NM3o0X1ViX1VUZ2FGcklTalBMVFN2WDg2VnBFYURNaTM00gF3QVVfeXFMTk1uQ0Q3SzU3Tmg4WURELVV1Zi1zMFBMWmxibFRud0FUZzRFWnQ2ZnFQdWJYZXU1UmpZWEg3MlRXQmJmSU9vbC1hUWVtdUpVQ2d3N2FxU2hrTnhzWHV5alRyMS1ZeV9QS2NnTkhTU1plNVVIOUJZTTg?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "https://news.google.com/rss/articles/CBMiW0FVX3lxTE4zaVdZRTJvTlhWR1IwM0lZU19NbW82QnlSdnJuZHByS2pEcXdoODlEMGhoOTY1MWJhMTNWeDZqbDVZdUh0eHFnTk5jSENUU2Q0b1RmWlR0T3pzcDA?oc=5",
    "뉴스기사2_날짜": "2026-02-08",
    "뉴스기사3_URL": "https://news.google.com/rss/articles/CBMiW0FVX3lxTE5MSFNkTUhwS19XN0hsZVZtNmFuMUVpbGVxMXlVWjdkYmdKbnllSnJLeFR0Q0ppZ1dQb0pKMVVKUlJGclM0anp4YVlwTm5Ca3hFNGNyLURIaFNzY1nSAWBBVV95cUxNT1hMajM4N0R2eUhncnQ0aHEtNmJyQWVNZktZakw3VGpBTFMydmhuU29tVFM0T2ZOQTFKWlpMVklHSUgzdUVnU1NqZXpjMko3MU5sVGM5TU5lYU1iOFpLZ3g?oc=5",
    "뉴스기사3_날짜": "2026-02-08",
    "조회수": ""
  },
  {
    "순위": 2,
    "제목": "[속보] '尹대통령실 PC 초기화' 정진석, 경찰 피의자 출석 - 중앙일보",
    "추천점수": 10.0,
    "키워드": "속보",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiVkFVX3lxTE5MbWRNTnNWTFl5YTF6OXdoV3VYaWRSZThhLUs0ZWV4dUpKVG9Zc2tTSWhhcVNDSkJTNFRMM3NJSDFFNFc2MlFrVnZZM0xtNzNfUGVHSGJn?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "https://news.google.com/rss/articles/CBMiW0FVX3lxTE5MSFNkTUhwS19XN0hsZVZtNmFuMUVpbGVxMXlVWjdkYmdKbnllSnJLeFR0Q0ppZ1dQb0pKMVVKUlJGclM0anp4YVlwTm5Ca3hFNGNyLURIaFNzY1nSAWBBVV95cUxNT1hMajM4N0R2eUhncnQ0aHEtNmJyQWVNZktZakw3VGpBTFMydmhuU29tVFM0T2ZOQTFKWlpMVklHSUgzdUVnU1NqZXpjMko3MU5sVGM5TU5lYU1iOFpLZ3g?oc=5",
    "뉴스기사2_날짜": "2026-02-08",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 3,
    "제목": "[속보] 당정 \"대미투자특별법, 3월 초 여야 합의 통과되도록 최선 다할 것\" - newspim.com",
    "추천점수": 10.0,
    "키워드": "속보",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiXEFVX3lxTE9PeXktM1BrYlQ4RkxESEEwcE5tMUY5cFNldFJWQmM0ZURsakVKdFRsblNfOEMtSS0xVmh3Y1J4N19nUjFkU0NPbEhMN2tXQ1FibnN4Z182dlNuMXcw?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 4,
    "제목": "“용광로에 폐기” 지시 밝혀질까···‘대통령실 PC초기화 의혹’ 정진석 피의자 소환 - 경향신문",
    "추천점수": 7.0,
    "키워드": "의혹",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE94Rnd6Z2wwTzIzWV9QaDRZVkVpQ21td1JvVUFLajhuTmFWSzBzNzJkcllFVkxtWFRCNGZKWWlMSXFjZDlRREFHdmNkNEJHaVZaU09CLXU4Y0ZzQdIBX0FVX3lxTE5KdlpIc3VLT2s2Sk1JM2NPdm80MzM0ekhQQ3RvSkZxbWFZT2ppRFM1bW5FaGlObjNUV0U3WFVrLVlvNXdMbDAyVEg4RWszb25WR3JfM0N4QWwtZjRQVDNF?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "https://news.google.com/rss/articles/CBMiW0FVX3lxTE4zaVdZRTJvTlhWR1IwM0lZU19NbW82QnlSdnJuZHByS2pEcXdoODlEMGhoOTY1MWJhMTNWeDZqbDVZdUh0eHFnTk5jSENUU2Q0b1RmWlR0T3pzcDA?oc=5",
    "뉴스기사2_날짜": "2026-02-08",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 5,
    "제목": "경찰, ‘尹대통령실 PC 초기화 의혹’ 정진석 전 실장 소환 - KBS 뉴스",
    "추천점수": 7.0,
    "키워드": "의혹",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiW0FVX3lxTE4zaVdZRTJvTlhWR1IwM0lZU19NbW82QnlSdnJuZHByS2pEcXdoODlEMGhoOTY1MWJhMTNWeDZqbDVZdUh0eHFnTk5jSENUU2Q0b1RmWlR0T3pzcDA?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "https://news.google.com/rss/articles/CBMid0FVX3lxTFBIVnl3alpjbnNwOGMySVZHMUhieW40YUFYYkE4dDhGaWZVNkRmRDZnN05NSWY0QlJNS3R3aHprYzdZUzNVdjA0SDl3NFpjZmI5YWstSi1NM3o0X1ViX1VUZ2FGcklTalBMVFN2WDg2VnBFYURNaTM00gF3QVVfeXFMTk1uQ0Q3SzU3Tmg4WURELVV1Zi1zMFBMWmxibFRud0FUZzRFWnQ2ZnFQdWJYZXU1UmpZWEg3MlRXQmJmSU9vbC1hUWVtdUpVQ2d3N2FxU2hrTnhzWHV5alRyMS1ZeV9QS2NnTkhTU1plNVVIOUJZTTg?oc=5",
    "뉴스기사2_날짜": "2026-02-08",
    "뉴스기사3_URL": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE94Rnd6Z2wwTzIzWV9QaDRZVkVpQ21td1JvVUFLajhuTmFWSzBzNzJkcllFVkxtWFRCNGZKWWlMSXFjZDlRREFHdmNkNEJHaVZaU09CLXU4Y0ZzQdIBX0FVX3lxTE5KdlpIc3VLT2s2Sk1JM2NPdm80MzM0ekhQQ3RvSkZxbWFZT2ppRFM1bW5FaGlObjNUV0U3WFVrLVlvNXdMbDAyVEg4RWszb25WR3JfM0N4QWwtZjRQVDNF?oc=5",
    "뉴스기사3_날짜": "2026-02-08",
    "조회수": ""
  },
  {
    "순위": 6,
    "제목": "‘차은우 리스크’ 맞닥뜨린 넷플릭스 ‘원더풀스’…2분기 공개, 예정대로 할까",
    "추천점수": 7.0,
    "키워드": "공개",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/028/0002790543?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 7,
    "제목": "한동훈, 토크콘서트서 “제 풀에 꺾여 그만 둘 거란 기대 접어야”",
    "추천점수": 3.0,
    "키워드": "기대",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/366/0001141267?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 8,
    "제목": "국세청장 “‘백만장자’ 이민 2400명 아닌 139명…대한상의 정보 왜곡”",
    "추천점수": 3.0,
    "키워드": "정보",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/028/0002790544?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 9,
    "제목": "여야, 9일부터 사흘간 대정부질문…\"李정부 성과 강조\" \"부동산·관세 추궁\" - 뉴스1",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE1iSktzV1BLcHBPblZIWEk5WVNSZWlNRjdBQXU3Qk9UTTdMSmstRExsUU1qU1lFc1hGQWVhZExVRmhOeGRjVk9XUEo1V1FpMnpKc0R5dldCVmJoZw?oc=5",
    "업로드일": "2026-02-07",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 10,
    "제목": "인천 해사전문법원, 국회 첫 관문 통과 - 시니어오늘",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMib0FVX3lxTFBIQTRteFhFa05Xd2VBazRQRGpiTVdkTjhqRnNwX0hXUWc3UXMxOGttRzVsWWJ5dE9fdE1yR1pqQjRxcG5NcTE4bVlYVlMyTklZSlppTlNoYW85eldzTVN5eTRTMkVEdXhBQ1B1MzRtNA?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 11,
    "제목": "여야, 9일부터 대정부질문…12일 본회의선 여야 합의 법안 처리 - 대한경제",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMidEFVX3lxTE9FdUgtRWI2YVRxUGdUd09vRXQwaXhXcF9fNkV0Z1VVMGhKTnludjlLWWhoRDVEY05oX3B6NzZZWGRTRDVQa3JpRTlPM1dUOHhXbHFEVF9Hc2hPNEdOWk96dGxzRnIwUDlQbi1tUkJNX1VNellX?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 12,
    "제목": "경찰, '尹대통령실 PC 초기화' 정진석 피의자 소환 - yna.co.kr",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiW0FVX3lxTE5MSFNkTUhwS19XN0hsZVZtNmFuMUVpbGVxMXlVWjdkYmdKbnllSnJLeFR0Q0ppZ1dQb0pKMVVKUlJGclM0anp4YVlwTm5Ca3hFNGNyLURIaFNzY1nSAWBBVV95cUxNT1hMajM4N0R2eUhncnQ0aHEtNmJyQWVNZktZakw3VGpBTFMydmhuU29tVFM0T2ZOQTFKWlpMVklHSUgzdUVnU1NqZXpjMko3MU5sVGM5TU5lYU1iOFpLZ3g?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "https://news.google.com/rss/articles/CBMid0FVX3lxTFBIVnl3alpjbnNwOGMySVZHMUhieW40YUFYYkE4dDhGaWZVNkRmRDZnN05NSWY0QlJNS3R3aHprYzdZUzNVdjA0SDl3NFpjZmI5YWstSi1NM3o0X1ViX1VUZ2FGcklTalBMVFN2WDg2VnBFYURNaTM00gF3QVVfeXFMTk1uQ0Q3SzU3Tmg4WURELVV1Zi1zMFBMWmxibFRud0FUZzRFWnQ2ZnFQdWJYZXU1UmpZWEg3MlRXQmJmSU9vbC1hUWVtdUpVQ2d3N2FxU2hrTnhzWHV5alRyMS1ZeV9QS2NnTkhTU1plNVVIOUJZTTg?oc=5",
    "뉴스기사2_날짜": "2026-02-08",
    "뉴스기사3_URL": "https://news.google.com/rss/articles/CBMiVkFVX3lxTE5MbWRNTnNWTFl5YTF6OXdoV3VYaWRSZThhLUs0ZWV4dUpKVG9Zc2tTSWhhcVNDSkJTNFRMM3NJSDFFNFc2MlFrVnZZM0xtNzNfUGVHSGJn?oc=5",
    "뉴스기사3_날짜": "2026-02-08",
    "조회수": ""
  },
  {
    "순위": 13,
    "제목": "대미투자법·행정통합법·자사주소각..쟁점법안 심의 본격화 - fnnews.com",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "정치",
    "출처": "구글뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE0yN0gtanBiVWh6S2lZa1ROUUhnakdNT21NYzNocmREeUFuZnR5X09maVFrOFNDbUtPNHIxWXVUYWlTa1RiUDIxUHhQTEh0WHJrSmFqN3pRbzlRQdIBXkFVX3lxTE9QcU1rUWRLcGlscXlaVEZMU3RxbnhMRW1XV05VT0M1SGpQemtLN2poSmRCdmFqR1JhQmhlT1kwY2NReVpFXzkxM1FWYmRiUHZOczlVVXZPQlpLQXVYQ1E?oc=5",
    "업로드일": "2026-02-08",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 14,
    "제목": "보유량 12배 비트코인 뿌린 빗썸… 부실한 ‘장부 시스템’ 도마 위",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/366/0001141215?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 15,
    "제목": "‘눈보라’ 제주공항에 항공기 10편 추가 투입… 결항편 승객 2000명 수송",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/366/0001141260?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 16,
    "제목": "‘계엄 연루’ 군 간부 23명, 파면 불복…국방부에 항고",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/366/0001141265?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 17,
    "제목": "정원오 성동구청장, 서울시장 출마 공식화",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/366/0001141258?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 18,
    "제목": "‘명태균·김영선 무죄’ 판사, 기업서 국외 골프여행비 받아 약식기소",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/028/0002790556?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 19,
    "제목": "‘논스톱’ ‘남셋여셋’…그 많던 캠퍼스 청춘물은 다 어디로 갔을까",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/028/0002790533?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  },
  {
    "순위": 20,
    "제목": "김용태 “장동혁 체제는 윤 어게인…당 리더십, 윤 어게인에 못 맡겨”",
    "추천점수": 0.0,
    "키워드": "",
    "카테고리": "정치",
    "출처": "네이버뉴스",
    "유튜브_URL": "",
    "뉴스기사_URL": "https://n.news.naver.com/article/028/0002790519?ntype=RANKING",
    "업로드일": "",
    "뉴스기사2_URL": "",
    "뉴스기사2_날짜": "",
    "뉴스기사3_URL": "",
    "뉴스기사3_날짜": "",
    "조회수": ""
  }
];
var scraperStatus = {
  "youtube": "OK",
  "google": "OK",
  "naver": "OK"
};
